### ISSUE TITLE
How can I test on my own images?

### ISSUE THREAD

**Issue by zzzcccxx** [NilBiescas/CVC_internship#1]
Hello,
I am greatly inspired by your work and am very interested in it. However, I noticed that the training and testing seem to be only on the dataset. How can I test on my own images and draw bounding boxes? Could you please provide detailed steps? As I am just starting to learn about this, I would be very grateful for your guidance.

**Comment by zzzcccxx** [comment]
Additionally, I am curious about how to create my own dataset for training if I want to define it myself. Thank you for your response.

**Comment by NilBiescas** [comment]
Hey thanks for the comments !! Right now i have some things and i would need to change some parts of the code ! During this month I will make the changes and give you an answer as soon as possible !

**Comment by zzzcccxx** [comment]
That's wonderful, I'm really looking forward to it.

**Comment by NilBiescas** [comment]
For drawing bounding boxes, either you have them as gt or you use an object detector to find them. Yolo for instance.
I have added a part explaining how can you train on your own graphs. I hope it helps. I still need to improve it. If you have any questions or doubts, feel free to ask !
